"""
    Provides data structures to handle ORCA files.
"""


import csv

# third party imports
import numpy as np

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# MODULE STRUCTURE
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
#
# + class Geometry()
#   - __init__()
#   - read_xyz(xyz_file)
#   - write_xyz(xyz_file)
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

class Geometry():
   
    """
    ORCA Geometry Container

    Attributes:
    ----------

     - atoms (dict): dictionary with positions of the atoms (fractional)
     - lat_vecs (array): supercell shape 

    """

    def __init__(self):

        self.species   = []
        self.positions = []
        self.ghost     = []

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

    def read_xyz(self, xyz_file):

        with open(xyz_file, "r") as f:
            
            self.nats = int(f.readline().split()[0])
            f.readline() # comment line
            
            self.species = []
            self.positions = np.zeros((self.nats, 3))

            for i in range(self.nats):

                line = f.readline().split()
                self.species.append(line[0])
                self.positions[i,:] = np.array([float(x) for x in line[1:4]])


    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

    def write_xyz(self, xyz_file):

        with open(xyz_file, "w") as f:

            tsv = csv.writer(f, delimiter="\t")

            tsv.writerow([self.nats])
            tsv.writerow([".xyz automatically generated by WHALE."])

            for i in range(self.nats):
                line = [self.species[i]] + ["{:10.8F}".format(d) for d in self.positions[i,:]]
                tsv.writerow(line)

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #






















